sudo: required
services:
    - docker

before_install:
    - docker build -t ryan/docker-react -f Dockerfile.dev .

script:
    - docker run ryan/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-northeast-2-604334539786"
    bucket_path: "docker-react"
    on:
        branch: master